spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2?charset=utf-8&serverTimezone=UTC
    username: root
    password: root
    platform: mysql
    initialization-mode: always
server:
  port: 8085